/**
 * Verify the caller's JWT and hand the handler a clinic-scoped database client.
 *
 * This lived in `src/integrations/supabase/auth-middleware.ts`, whose first line
 * reads "This file is automatically generated. Do not edit it directly." The
 * ES256 workaround below had been hand-edited into it, so a regeneration — and
 * this branch syncs to Lovable — would have silently removed the only thing
 * making server functions work. It belongs in a file we own.
 */
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import { clinicScoped } from "@/lib/auth/clinic-scope.server";

/** New-style Supabase keys are opaque strings, not bearer JWTs. */
function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );
    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }
    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function serviceClient(url: string, key: string) {
  return createClient<Database>(url, key, {
    global: { fetch: createSupabaseFetch(key) },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });
}

/**
 * Which clinic this request belongs to. Resolved here rather than in
 * `loadIdentity` because the client has to be wrapped before any handler can
 * reach it, and `current_clinic_id()` is useless to us — the service-role
 * client has no `auth.uid()`.
 */
async function resolveClinicId(
  db: ReturnType<typeof serviceClient>,
  userId: string,
): Promise<string | null> {
  const { data: profile, error: profileError } = await db
    .from("profiles")
    .select("clinic_id")
    .eq("id", userId)
    .maybeSingle();
  // A failed read here would silently drop the caller into the unscoped
  // bootstrap path, so it has to be loud.
  if (profileError) throw new Error(`Could not resolve your clinic: ${profileError.message}`);
  if (profile?.clinic_id) return profile.clinic_id;

  const { data: patient, error: patientError } = await db
    .from("patients")
    .select("clinic_id")
    .eq("user_id", userId)
    .maybeSingle();
  if (patientError) throw new Error(`Could not resolve your clinic: ${patientError.message}`);
  return patient?.clinic_id ?? null;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();
    if (!request?.headers) throw new Error("Unauthorized: No request headers available");

    const authHeader = request.headers.get("authorization");
    if (!authHeader) throw new Error("Unauthorized: No authorization header provided");
    if (!authHeader.startsWith("Bearer "))
      throw new Error("Unauthorized: Only Bearer tokens are supported");

    const token = authHeader.replace("Bearer ", "");
    if (!token) throw new Error("Unauthorized: No token provided");
    if (token.split(".").length !== 3) throw new Error("Unauthorized: Invalid token");

    const authClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY) },
      auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
    });

    const { data, error } = await authClient.auth.getClaims(token);
    if (error || !data?.claims) throw new Error("Unauthorized: Invalid token");
    if (!data.claims.sub) throw new Error("Unauthorized: No user ID found in token");

    // This project's user access tokens are ES256 (asymmetric signing keys) and
    // PostgREST rejects them with PGRST303 "JWT issued at future". So the JWT is
    // verified through Auth above, and the database is queried with the service
    // role. RLS does not apply to that client, which is why authorization lives
    // in auth/guards.server.ts and clinic isolation in the wrapper below.
    const SUPABASE_SERVICE_ROLE_KEY = process.env["SUPABASE_SERVICE_ROLE_KEY"];
    if (!SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error(
        "Missing SUPABASE_SERVICE_ROLE_KEY. Copy the service_role (secret) key from Supabase > Project Settings > API into .env.",
      );
    }

    const db = serviceClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const clinicId = await resolveClinicId(db, data.claims.sub);

    return next({
      context: {
        supabase: clinicScoped(db, clinicId),
        clinicId,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
