/**
 * Practitioner invoices to the clinic: the email that carries one, and the
 * daily delivery of invoices scheduled for the 1st. Production and demo call
 * `deliverScheduledInvoices` from their outbox drain with their own store.
 */
import { sendEmail } from "@/lib/comms/email.server";
import { buildInvoiceDocument, invoiceDocumentHtml } from "@/lib/invoice-document";
import { MONTHS_LONG, dayKeyOf, parseDayKey } from "@/lib/staff-schedule";

export type InvoiceRow = {
  id: string;
  user_id: string;
  number: string;
  period_start: string;
  period_end: string;
  recipient: "payroll" | "owner" | string;
  note?: string | null;
  status: "scheduled" | "sent" | "paid" | string;
  scheduled_for?: string | null;
  amount: number;
  treatments: number;
};

export type InvoiceParty = { name: string; email: string | null; jobTitle?: string | null };

export function invoicePeriodLabel(inv: Pick<InvoiceRow, "period_start">): string {
  const { year, month } = parseDayKey(inv.period_start);
  return `${MONTHS_LONG[month - 1]} ${year}`;
}

export function invoiceMoney(n: number): string {
  return `£${n.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/** Subject and text body of the invoice email. */
export function invoiceEmail(
  inv: InvoiceRow,
  from: InvoiceParty,
  clinicName: string,
): { subject: string; body: string } {
  const period = invoicePeriodLabel(inv);
  const lines = [
    `Invoice ${inv.number} from ${from.name}${from.jobTitle ? `, ${from.jobTitle}` : ""}`,
    `To: ${clinicName}`,
    "",
    `Period: ${period} (${inv.period_start} to ${inv.period_end})`,
    `Treatments delivered, practitioner share: ${inv.treatments} treatments`,
    `Total due: ${invoiceMoney(inv.amount)}`,
    "",
    inv.note ? `Note: ${inv.note}` : null,
    inv.note ? "" : null,
    `Generated by SQINOS from completed treatments in the diary.`,
  ].filter((l): l is string => l !== null);
  return {
    subject: `Invoice ${inv.number} · ${period} · ${invoiceMoney(inv.amount)}`,
    body: lines.join("\n"),
  };
}

/** Where an invoice goes: payroll = the clinic's email; owner = the owner's own email. */
export function invoiceRecipientEmail(
  recipient: string,
  clinic: { email: string | null },
  owner: { email: string | null },
): string | null {
  return recipient === "owner" ? owner.email : clinic.email;
}

export type InvoiceStore = {
  clinicName: string;
  clinicEmail: string | null;
  /** Owner(s) of the clinic, for the "owner" recipient and the notification. */
  owners: { id: string; email: string | null }[];
  practitioner(userId: string): Promise<InvoiceParty>;
  markSent(id: string, sentAt: string): Promise<void>;
  notifyOwners(inv: InvoiceRow, fromName: string): Promise<void>;
};

/** Send one invoice now: email plus a notification to the owner(s), then mark it sent. */
export async function sendInvoiceNow(
  store: InvoiceStore,
  inv: InvoiceRow,
  now = new Date(),
): Promise<{ emailed: boolean }> {
  const from = await store.practitioner(inv.user_id);
  const owner = store.owners[0] ?? { id: "", email: null };
  const to = invoiceRecipientEmail(inv.recipient, { email: store.clinicEmail }, owner);
  let emailed = false;
  if (to) {
    const mail = invoiceEmail(inv, from, store.clinicName);
    const { year, month } = parseDayKey(inv.period_start);
    const html = invoiceDocumentHtml(
      buildInvoiceDocument({
        number: inv.number,
        issuedOn: dayKeyOf(now),
        year,
        month,
        from: { name: from.name, line1: from.jobTitle ?? null, line2: from.email },
        billTo: {
          name: store.clinicName,
          line1: inv.recipient === "owner" ? "Clinic owner" : "Payroll team",
          line2: to,
        },
        qty: inv.treatments,
        amount: inv.amount,
        note: inv.note ?? null,
        status: "sent",
      }),
    );
    const result = await sendEmail({ to, subject: mail.subject, body: mail.body, html });
    emailed = result.ok;
    if (!result.ok) console.error(`[invoices] email for ${inv.number} failed: ${result.error}`);
  }
  await store.notifyOwners(inv, from.name);
  await store.markSent(inv.id, now.toISOString());
  return { emailed };
}

/** Which scheduled invoices are due on `todayKey` (YYYY-MM-DD). */
export function dueInvoices<T extends Pick<InvoiceRow, "status" | "scheduled_for">>(
  rows: readonly T[],
  todayKey: string,
): T[] {
  return rows.filter(
    (r) => r.status === "scheduled" && Boolean(r.scheduled_for) && r.scheduled_for! <= todayKey,
  );
}

/** Deliver every due scheduled invoice; called at the start of the outbox drain. */
export async function deliverScheduledInvoices(
  store: InvoiceStore,
  rows: readonly InvoiceRow[],
  todayKey: string,
  now = new Date(),
): Promise<number> {
  let sent = 0;
  for (const inv of dueInvoices(rows, todayKey)) {
    await sendInvoiceNow(store, inv, now);
    sent += 1;
  }
  return sent;
}
