export const PERMISSION_KEYS = [
  "patients.edit",
  "treatments.record",
  "documents.send",
  "photos.manage",
  "appointments.edit",
  "comms.send",
  "notifications.delete",
  "reports.insights",
  "reports.retention",
  "reports.performance",
  "team.view",
  "team.approve_changes",
  "settings.treatments",
  "tasks.delete",
  "offers.manage",
  "view.dashboard",
  "view.dashboard.diary",
  "view.dashboard.attention",
  "view.dashboard.followups",
  "view.dashboard.pauses",
  "view.dashboard.journeys",
  "view.schedule",
  "view.patients",
  "view.patients.records",
  "view.patients.board",
  "view.patients.record",
  "view.patients.treatments",
  "view.patients.photos",
  "view.patients.documents",
  "view.patients.history",
  "view.patients.from_patient",
  "view.patients.contact",
  "view.profile",
  "view.settings",
  "view.team.current",
  "view.team.former",
  "view.shell",
  "view.shell.dock",
  "view.shell.search",
  "view.shell.alerts",
  "view.insights.pipeline",
  "view.insights.book",
  "view.earnings",
  "view.portal.home",
  "view.portal.plan",
  "view.portal.plan.overview",
  "view.portal.plan.timeline",
  "view.portal.plan.journal",
  "view.portal.plan.routine",
  "view.portal.clinic",
  "view.portal.records",
  "view.portal.appointments",
  "view.portal.resources",
  "view.portal.billing",
  "view.portal.settings",
  "view.portal.chat",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];

export const PERMISSION_META: Record<PermissionKey, { label: string; description: string }> = {
  "patients.edit": {
    label: "Patient records",
    description: "Create patients and keep their contact details and clinical summary current.",
  },
  "treatments.record": {
    label: "Record treatments & notes",
    description: "Log treatments, write visit notes and sign off medical history reviews.",
  },
  "documents.send": {
    label: "Send documents",
    description: "Issue consent forms, treatment plans and aftercare to patients.",
  },
  "photos.manage": {
    label: "Clinical photos",
    description: "Upload before and after photographs to a patient's record.",
  },
  "appointments.edit": {
    label: "Manage the diary",
    description: "Book, edit, reschedule and cancel appointments.",
  },
  "comms.send": {
    label: "Send messages",
    description: "Message patients from the clinic and raise alerts to the team.",
  },
  "notifications.delete": {
    label: "Clear notifications",
    description: "Dismiss and complete alerts in the notification bell.",
  },
  "reports.insights": {
    label: "Insights",
    description: "See the marketing and sales insights page, website funnel and product bestsellers.",
  },
  "reports.retention": {
    label: "Retention report",
    description: "See the retention dashboard, at-risk patients and recall tools.",
  },
  "reports.performance": {
    label: "Performance & earnings",
    description: "See practitioner KPIs, clinic earnings and the commission split.",
  },
  "team.view": {
    label: "Team & staff details",
    description:
      "Open the team page and staff profiles. Everyone can view profile details and chat; document files stay with managers. Only managers can edit profiles.",
  },
  "team.approve_changes": {
    label: "Approve profile changes",
    description: "Review and approve profile change requests from staff.",
  },
  "settings.treatments": {
    label: "Treatments & colours",
    description: "Add or edit treatments, treatment colours and clinic details.",
  },
  "tasks.delete": {
    label: "Delete tasks",
    description: "Remove recall and follow-up tasks from the task lists.",
  },
  "offers.manage": {
    label: "Design and automate offers",
    description:
      "Design offer templates, switch stage automation on or off and see who each offer went to. Sending an offer to a patient needs Send messages.",
  },
  "view.dashboard": { label: "Dashboard", description: "Open the clinic dashboard." },
  "view.dashboard.diary": { label: "Dashboard diary", description: "See today's diary on the dashboard." },
  "view.dashboard.attention": { label: "Attention needed", description: "See the attention list on the dashboard." },
  "view.dashboard.followups": { label: "Follow-up tasks", description: "See follow-up tasks on the dashboard." },
  "view.dashboard.pauses": { label: "Pause requests", description: "See plan pause requests on the dashboard." },
  "view.dashboard.journeys": { label: "Treatment journeys", description: "See treatment journeys on the dashboard." },
  "view.schedule": { label: "Diary", description: "Open the clinic diary." },
  "view.patients": { label: "Patients", description: "Open the patient list." },
  "view.patients.records": { label: "Patient records tab", description: "See the records tab on the patient list." },
  "view.patients.board": { label: "Journey board", description: "See the journey board on the patient list." },
  "view.patients.record": { label: "Patient record", description: "Open an individual patient record." },
  "view.patients.treatments": { label: "Treatments tab", description: "See the treatments tab on a patient record." },
  "view.patients.photos": { label: "Before and after tab", description: "See clinical photos on a patient record." },
  "view.patients.documents": { label: "Documents tab", description: "See documents on a patient record." },
  "view.patients.history": { label: "History updates tab", description: "See history updates on a patient record." },
  "view.patients.from_patient": { label: "From the patient tab", description: "See the patient's portal updates on their record." },
  "view.patients.contact": { label: "Contact tab", description: "See contact and message preferences on a patient record." },
  "view.profile": { label: "My profile", description: "Open your own staff profile." },
  "view.settings": { label: "Settings page", description: "Open clinic settings. Editing treatments still needs Treatments and colours." },
  "view.team.current": { label: "Current staff", description: "See the current staff tab on Team." },
  "view.team.former": { label: "Former staff", description: "See the former staff tab on Team." },
  "view.shell": { label: "Clinic chrome", description: "See the staff search, alerts and dock." },
  "view.shell.dock": { label: "Staff dock", description: "See the floating staff dock." },
  "view.shell.search": { label: "Patient search", description: "See the sidebar patient search." },
  "view.shell.alerts": { label: "Alert toolbar", description: "See the staff alert, notes and sent-alert controls." },
  "view.insights.pipeline": { label: "Insights pipeline", description: "See the pipeline tab on Insights." },
  "view.insights.book": { label: "Insights book", description: "See the book tab on Insights." },
  "view.earnings": { label: "My earnings", description: "Open your own earnings page." },
  "view.portal.home": { label: "Portal home", description: "Open the patient home page." },
  "view.portal.plan": { label: "Skin plan", description: "Open the skin plan." },
  "view.portal.plan.overview": { label: "Plan overview", description: "See the plan overview." },
  "view.portal.plan.timeline": { label: "Plan timeline", description: "See the plan timeline." },
  "view.portal.plan.journal": { label: "Journal", description: "See the patient journal." },
  "view.portal.plan.routine": { label: "Skincare routine", description: "See the skincare routine." },
  "view.portal.clinic": { label: "My clinic", description: "Open My clinic." },
  "view.portal.records": { label: "My records", description: "Open the patient profile and records." },
  "view.portal.appointments": { label: "Appointments", description: "Open the patient's appointments." },
  "view.portal.resources": { label: "Resources", description: "Open patient resources." },
  "view.portal.billing": { label: "Billing", description: "Open patient billing." },
  "view.portal.settings": { label: "Portal settings", description: "Open patient communication settings." },
  "view.portal.chat": { label: "Portal chat", description: "See the patient chat dock." },
};

/** Display grouping for the owner's access grid and the effective-permissions panel. */
export const PERMISSION_GROUPS: { label: string; keys: PermissionKey[] }[] = [
  {
    label: "Clinical record",
    keys: ["patients.edit", "treatments.record", "documents.send", "photos.manage"],
  },
  { label: "Diary", keys: ["appointments.edit"] },
  { label: "Communication", keys: ["comms.send", "notifications.delete"] },
  { label: "Marketing", keys: ["offers.manage"] },
  { label: "Reports", keys: ["reports.insights", "reports.retention", "reports.performance"] },
  { label: "Team", keys: ["team.view", "team.approve_changes"] },
  { label: "Clinic settings", keys: ["settings.treatments", "tasks.delete"] },
  {
    label: "Visibility",
    keys: [
      "view.dashboard",
      "view.dashboard.diary",
      "view.dashboard.attention",
      "view.dashboard.followups",
      "view.dashboard.pauses",
      "view.dashboard.journeys",
      "view.schedule",
      "view.patients",
      "view.patients.records",
      "view.patients.board",
      "view.patients.record",
      "view.patients.treatments",
      "view.patients.photos",
      "view.patients.documents",
      "view.patients.history",
      "view.patients.from_patient",
      "view.patients.contact",
      "view.profile",
      "view.settings",
      "view.team.current",
      "view.team.former",
      "view.shell",
      "view.shell.dock",
      "view.shell.search",
      "view.shell.alerts",
      "view.insights.pipeline",
      "view.insights.book",
      "view.earnings",
      "view.portal.home",
      "view.portal.plan",
      "view.portal.plan.overview",
      "view.portal.plan.timeline",
      "view.portal.plan.journal",
      "view.portal.plan.routine",
      "view.portal.clinic",
      "view.portal.records",
      "view.portal.appointments",
      "view.portal.resources",
      "view.portal.billing",
      "view.portal.settings",
      "view.portal.chat",
    ],
  },
];

type IdentityLike =
  | { isOwner?: boolean; isManager?: boolean; permissions?: string[] }
  | null
  | undefined;

/** Clinic owners always hold every capability; other staff need an explicit grant. */
export function can(identity: IdentityLike, key: PermissionKey) {
  if (!identity) return false;
  if (identity.isOwner) return true;
  return (identity.permissions ?? []).includes(key);
}
