/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedMyRecordRouteImport } from './routes/_authenticated/my-record'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRetentionRouteImport } from './routes/_authenticated/retention'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team.index'
import { Route as AuthenticatedTeamIdRouteImport } from './routes/_authenticated/team.$id'
import { Route as ApiCommsDrainRouteImport } from './routes/api.comms.drain'
import { Route as ApiCommsWebhooksResendRouteImport } from './routes/api.comms.webhooks.resend'
import { Route as ApiCommsWebhooksTwilioRouteImport } from './routes/api.comms.webhooks.twilio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRecordRoute = AuthenticatedMyRecordRouteImport.update({
  id: '/my-record',
  path: '/my-record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetentionRoute = AuthenticatedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const AuthenticatedTeamIdRoute = AuthenticatedTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const ApiCommsDrainRoute = ApiCommsDrainRouteImport.update({
  id: '/api/comms/drain',
  path: '/api/comms/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommsWebhooksResendRoute = ApiCommsWebhooksResendRouteImport.update({
  id: '/api/comms/webhooks/resend',
  path: '/api/comms/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommsWebhooksTwilioRoute = ApiCommsWebhooksTwilioRouteImport.update({
  id: '/api/comms/webhooks/twilio',
  path: '/api/comms/webhooks/twilio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/my-record': typeof AuthenticatedMyRecordRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/my-record': typeof AuthenticatedMyRecordRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/my-record': typeof AuthenticatedMyRecordRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/retention': typeof AuthenticatedRetentionRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/earnings'
    | '/my-record'
    | '/performance'
    | '/profile'
    | '/retention'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/auth/callback'
    | '/auth/reset'
    | '/patients/$id'
    | '/team/$id'
    | '/api/comms/drain'
    | '/patients/'
    | '/team/'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/earnings'
    | '/my-record'
    | '/performance'
    | '/profile'
    | '/retention'
    | '/schedule'
    | '/settings'
    | '/auth/callback'
    | '/auth/reset'
    | '/patients/$id'
    | '/team/$id'
    | '/api/comms/drain'
    | '/patients'
    | '/team'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/earnings'
    | '/_authenticated/my-record'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/retention'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/auth/callback'
    | '/auth/reset'
    | '/_authenticated/patients/$id'
    | '/_authenticated/team/$id'
    | '/api/comms/drain'
    | '/_authenticated/patients/'
    | '/_authenticated/team/'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRoute
  ApiCommsDrainRoute: typeof ApiCommsDrainRoute
  ApiCommsWebhooksResendRoute: typeof ApiCommsWebhooksResendRoute
  ApiCommsWebhooksTwilioRoute: typeof ApiCommsWebhooksTwilioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-record': {
      id: '/_authenticated/my-record'
      path: '/my-record'
      fullPath: '/my-record'
      preLoaderRoute: typeof AuthenticatedMyRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retention': {
      id: '/_authenticated/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthenticatedRetentionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/team/$id': {
      id: '/_authenticated/team/$id'
      path: '/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof AuthenticatedTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/api/comms/drain': {
      id: '/api/comms/drain'
      path: '/api/comms/drain'
      fullPath: '/api/comms/drain'
      preLoaderRoute: typeof ApiCommsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comms/webhooks/resend': {
      id: '/api/comms/webhooks/resend'
      path: '/api/comms/webhooks/resend'
      fullPath: '/api/comms/webhooks/resend'
      preLoaderRoute: typeof ApiCommsWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comms/webhooks/twilio': {
      id: '/api/comms/webhooks/twilio'
      path: '/api/comms/webhooks/twilio'
      fullPath: '/api/comms/webhooks/twilio'
      preLoaderRoute: typeof ApiCommsWebhooksTwilioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamIdRoute: typeof AuthenticatedTeamIdRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamIdRoute: AuthenticatedTeamIdRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedMyRecordRoute: typeof AuthenticatedMyRecordRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRetentionRoute: typeof AuthenticatedRetentionRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedMyRecordRoute: AuthenticatedMyRecordRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRetentionRoute: AuthenticatedRetentionRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRoute,
  ApiCommsDrainRoute: ApiCommsDrainRoute,
  ApiCommsWebhooksResendRoute: ApiCommsWebhooksResendRoute,
  ApiCommsWebhooksTwilioRoute: ApiCommsWebhooksTwilioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
