/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedMyRecordRouteImport } from './routes/_authenticated/my-record'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRetentionRouteImport } from './routes/_authenticated/retention'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as DTokenRouteImport } from './routes/d.$token'
import { Route as UTokenRouteImport } from './routes/u.$token'
import { Route as AuthenticatedMyRecordIndexRouteImport } from './routes/_authenticated/my-record.index'
import { Route as AuthenticatedMyRecordAppointmentsRouteImport } from './routes/_authenticated/my-record.appointments'
import { Route as AuthenticatedMyRecordBillingRouteImport } from './routes/_authenticated/my-record.billing'
import { Route as AuthenticatedMyRecordClinicRouteImport } from './routes/_authenticated/my-record.clinic'
import { Route as AuthenticatedMyRecordRecordsRouteImport } from './routes/_authenticated/my-record.records'
import { Route as AuthenticatedMyRecordResourcesRouteImport } from './routes/_authenticated/my-record.resources'
import { Route as AuthenticatedMyRecordSettingsRouteImport } from './routes/_authenticated/my-record.settings'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsIdRouteImport } from './routes/_authenticated/patients.$id'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team.index'
import { Route as AuthenticatedTeamIdRouteImport } from './routes/_authenticated/team.$id'
import { Route as ApiCommsDrainRouteImport } from './routes/api.comms.drain'
import { Route as ApiInsightsEventsRouteImport } from './routes/api.insights.events'
import { Route as AuthenticatedMyRecordPlanIndexRouteImport } from './routes/_authenticated/my-record.plan.index'
import { Route as AuthenticatedMyRecordPlanJournalRouteImport } from './routes/_authenticated/my-record.plan.journal'
import { Route as AuthenticatedMyRecordPlanRoutineRouteImport } from './routes/_authenticated/my-record.plan.routine'
import { Route as AuthenticatedMyRecordPlanTimelineRouteImport } from './routes/_authenticated/my-record.plan.timeline'
import { Route as ApiCommsUnsubscribeTokenRouteImport } from './routes/api.comms.unsubscribe.$token'
import { Route as ApiCommsWebhooksResendRouteImport } from './routes/api.comms.webhooks.resend'
import { Route as ApiCommsWebhooksTwilioRouteImport } from './routes/api.comms.webhooks.twilio'
import { Route as ApiDocumentsAccessTokenRouteImport } from './routes/api.documents.access.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyRecordRoute = AuthenticatedMyRecordRouteImport.update({
  id: '/my-record',
  path: '/my-record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetentionRoute = AuthenticatedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UTokenRoute = UTokenRouteImport.update({
  id: '/u/$token',
  path: '/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRecordIndexRoute =
  AuthenticatedMyRecordIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordAppointmentsRoute =
  AuthenticatedMyRecordAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordBillingRoute =
  AuthenticatedMyRecordBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordClinicRoute =
  AuthenticatedMyRecordClinicRouteImport.update({
    id: '/clinic',
    path: '/clinic',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordRecordsRoute =
  AuthenticatedMyRecordRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordResourcesRoute =
  AuthenticatedMyRecordResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordSettingsRoute =
  AuthenticatedMyRecordSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIdRoute = AuthenticatedPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const AuthenticatedTeamIdRoute = AuthenticatedTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTeamRoute,
} as any)
const ApiCommsDrainRoute = ApiCommsDrainRouteImport.update({
  id: '/api/comms/drain',
  path: '/api/comms/drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsEventsRoute = ApiInsightsEventsRouteImport.update({
  id: '/api/insights/events',
  path: '/api/insights/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRecordPlanIndexRoute =
  AuthenticatedMyRecordPlanIndexRouteImport.update({
    id: '/plan/',
    path: '/plan/',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordPlanJournalRoute =
  AuthenticatedMyRecordPlanJournalRouteImport.update({
    id: '/plan/journal',
    path: '/plan/journal',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordPlanRoutineRoute =
  AuthenticatedMyRecordPlanRoutineRouteImport.update({
    id: '/plan/routine',
    path: '/plan/routine',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const AuthenticatedMyRecordPlanTimelineRoute =
  AuthenticatedMyRecordPlanTimelineRouteImport.update({
    id: '/plan/timeline',
    path: '/plan/timeline',
    getParentRoute: () => AuthenticatedMyRecordRoute,
  } as any)
const ApiCommsUnsubscribeTokenRoute =
  ApiCommsUnsubscribeTokenRouteImport.update({
    id: '/api/comms/unsubscribe/$token',
    path: '/api/comms/unsubscribe/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCommsWebhooksResendRoute = ApiCommsWebhooksResendRouteImport.update({
  id: '/api/comms/webhooks/resend',
  path: '/api/comms/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommsWebhooksTwilioRoute = ApiCommsWebhooksTwilioRouteImport.update({
  id: '/api/comms/webhooks/twilio',
  path: '/api/comms/webhooks/twilio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsAccessTokenRoute = ApiDocumentsAccessTokenRouteImport.update({
  id: '/api/documents/access/$token',
  path: '/api/documents/access/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/my-record': typeof AuthenticatedMyRecordRouteWithChildren
  '/offers': typeof AuthenticatedOffersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/d/$token': typeof DTokenRoute
  '/u/$token': typeof UTokenRoute
  '/my-record/appointments': typeof AuthenticatedMyRecordAppointmentsRoute
  '/my-record/billing': typeof AuthenticatedMyRecordBillingRoute
  '/my-record/clinic': typeof AuthenticatedMyRecordClinicRoute
  '/my-record/records': typeof AuthenticatedMyRecordRecordsRoute
  '/my-record/resources': typeof AuthenticatedMyRecordResourcesRoute
  '/my-record/settings': typeof AuthenticatedMyRecordSettingsRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/api/insights/events': typeof ApiInsightsEventsRoute
  '/my-record/': typeof AuthenticatedMyRecordIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/my-record/plan/journal': typeof AuthenticatedMyRecordPlanJournalRoute
  '/my-record/plan/routine': typeof AuthenticatedMyRecordPlanRoutineRoute
  '/my-record/plan/timeline': typeof AuthenticatedMyRecordPlanTimelineRoute
  '/api/comms/unsubscribe/$token': typeof ApiCommsUnsubscribeTokenRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
  '/api/documents/access/$token': typeof ApiDocumentsAccessTokenRoute
  '/my-record/plan/': typeof AuthenticatedMyRecordPlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/retention': typeof AuthenticatedRetentionRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/d/$token': typeof DTokenRoute
  '/u/$token': typeof UTokenRoute
  '/my-record/appointments': typeof AuthenticatedMyRecordAppointmentsRoute
  '/my-record/billing': typeof AuthenticatedMyRecordBillingRoute
  '/my-record/clinic': typeof AuthenticatedMyRecordClinicRoute
  '/my-record/records': typeof AuthenticatedMyRecordRecordsRoute
  '/my-record/resources': typeof AuthenticatedMyRecordResourcesRoute
  '/my-record/settings': typeof AuthenticatedMyRecordSettingsRoute
  '/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/api/insights/events': typeof ApiInsightsEventsRoute
  '/my-record': typeof AuthenticatedMyRecordIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/my-record/plan/journal': typeof AuthenticatedMyRecordPlanJournalRoute
  '/my-record/plan/routine': typeof AuthenticatedMyRecordPlanRoutineRoute
  '/my-record/plan/timeline': typeof AuthenticatedMyRecordPlanTimelineRoute
  '/api/comms/unsubscribe/$token': typeof ApiCommsUnsubscribeTokenRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
  '/api/documents/access/$token': typeof ApiDocumentsAccessTokenRoute
  '/my-record/plan': typeof AuthenticatedMyRecordPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/portal': typeof PortalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/my-record': typeof AuthenticatedMyRecordRouteWithChildren
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/retention': typeof AuthenticatedRetentionRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset': typeof AuthResetRoute
  '/d/$token': typeof DTokenRoute
  '/u/$token': typeof UTokenRoute
  '/_authenticated/my-record/appointments': typeof AuthenticatedMyRecordAppointmentsRoute
  '/_authenticated/my-record/billing': typeof AuthenticatedMyRecordBillingRoute
  '/_authenticated/my-record/clinic': typeof AuthenticatedMyRecordClinicRoute
  '/_authenticated/my-record/records': typeof AuthenticatedMyRecordRecordsRoute
  '/_authenticated/my-record/resources': typeof AuthenticatedMyRecordResourcesRoute
  '/_authenticated/my-record/settings': typeof AuthenticatedMyRecordSettingsRoute
  '/_authenticated/patients/$id': typeof AuthenticatedPatientsIdRoute
  '/_authenticated/team/$id': typeof AuthenticatedTeamIdRoute
  '/api/comms/drain': typeof ApiCommsDrainRoute
  '/api/insights/events': typeof ApiInsightsEventsRoute
  '/_authenticated/my-record/': typeof AuthenticatedMyRecordIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/my-record/plan/journal': typeof AuthenticatedMyRecordPlanJournalRoute
  '/_authenticated/my-record/plan/routine': typeof AuthenticatedMyRecordPlanRoutineRoute
  '/_authenticated/my-record/plan/timeline': typeof AuthenticatedMyRecordPlanTimelineRoute
  '/api/comms/unsubscribe/$token': typeof ApiCommsUnsubscribeTokenRoute
  '/api/comms/webhooks/resend': typeof ApiCommsWebhooksResendRoute
  '/api/comms/webhooks/twilio': typeof ApiCommsWebhooksTwilioRoute
  '/api/documents/access/$token': typeof ApiDocumentsAccessTokenRoute
  '/_authenticated/my-record/plan/': typeof AuthenticatedMyRecordPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/earnings'
    | '/insights'
    | '/my-record'
    | '/offers'
    | '/performance'
    | '/profile'
    | '/retention'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/auth/callback'
    | '/auth/reset'
    | '/d/$token'
    | '/u/$token'
    | '/my-record/appointments'
    | '/my-record/billing'
    | '/my-record/clinic'
    | '/my-record/records'
    | '/my-record/resources'
    | '/my-record/settings'
    | '/patients/$id'
    | '/team/$id'
    | '/api/comms/drain'
    | '/api/insights/events'
    | '/my-record/'
    | '/patients/'
    | '/team/'
    | '/my-record/plan/journal'
    | '/my-record/plan/routine'
    | '/my-record/plan/timeline'
    | '/api/comms/unsubscribe/$token'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
    | '/api/documents/access/$token'
    | '/my-record/plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/earnings'
    | '/insights'
    | '/offers'
    | '/performance'
    | '/profile'
    | '/retention'
    | '/schedule'
    | '/settings'
    | '/auth/callback'
    | '/auth/reset'
    | '/d/$token'
    | '/u/$token'
    | '/my-record/appointments'
    | '/my-record/billing'
    | '/my-record/clinic'
    | '/my-record/records'
    | '/my-record/resources'
    | '/my-record/settings'
    | '/patients/$id'
    | '/team/$id'
    | '/api/comms/drain'
    | '/api/insights/events'
    | '/my-record'
    | '/patients'
    | '/team'
    | '/my-record/plan/journal'
    | '/my-record/plan/routine'
    | '/my-record/plan/timeline'
    | '/api/comms/unsubscribe/$token'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
    | '/api/documents/access/$token'
    | '/my-record/plan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/earnings'
    | '/_authenticated/insights'
    | '/_authenticated/my-record'
    | '/_authenticated/offers'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/retention'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/auth/callback'
    | '/auth/reset'
    | '/d/$token'
    | '/u/$token'
    | '/_authenticated/my-record/appointments'
    | '/_authenticated/my-record/billing'
    | '/_authenticated/my-record/clinic'
    | '/_authenticated/my-record/records'
    | '/_authenticated/my-record/resources'
    | '/_authenticated/my-record/settings'
    | '/_authenticated/patients/$id'
    | '/_authenticated/team/$id'
    | '/api/comms/drain'
    | '/api/insights/events'
    | '/_authenticated/my-record/'
    | '/_authenticated/patients/'
    | '/_authenticated/team/'
    | '/_authenticated/my-record/plan/journal'
    | '/_authenticated/my-record/plan/routine'
    | '/_authenticated/my-record/plan/timeline'
    | '/api/comms/unsubscribe/$token'
    | '/api/comms/webhooks/resend'
    | '/api/comms/webhooks/twilio'
    | '/api/documents/access/$token'
    | '/_authenticated/my-record/plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PortalRoute: typeof PortalRoute
  DTokenRoute: typeof DTokenRoute
  UTokenRoute: typeof UTokenRoute
  ApiCommsDrainRoute: typeof ApiCommsDrainRoute
  ApiInsightsEventsRoute: typeof ApiInsightsEventsRoute
  ApiCommsUnsubscribeTokenRoute: typeof ApiCommsUnsubscribeTokenRoute
  ApiCommsWebhooksResendRoute: typeof ApiCommsWebhooksResendRoute
  ApiCommsWebhooksTwilioRoute: typeof ApiCommsWebhooksTwilioRoute
  ApiDocumentsAccessTokenRoute: typeof ApiDocumentsAccessTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-record': {
      id: '/_authenticated/my-record'
      path: '/my-record'
      fullPath: '/my-record'
      preLoaderRoute: typeof AuthenticatedMyRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retention': {
      id: '/_authenticated/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthenticatedRetentionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$token': {
      id: '/u/$token'
      path: '/u/$token'
      fullPath: '/u/$token'
      preLoaderRoute: typeof UTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-record/': {
      id: '/_authenticated/my-record/'
      path: '/'
      fullPath: '/my-record/'
      preLoaderRoute: typeof AuthenticatedMyRecordIndexRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/appointments': {
      id: '/_authenticated/my-record/appointments'
      path: '/appointments'
      fullPath: '/my-record/appointments'
      preLoaderRoute: typeof AuthenticatedMyRecordAppointmentsRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/billing': {
      id: '/_authenticated/my-record/billing'
      path: '/billing'
      fullPath: '/my-record/billing'
      preLoaderRoute: typeof AuthenticatedMyRecordBillingRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/clinic': {
      id: '/_authenticated/my-record/clinic'
      path: '/clinic'
      fullPath: '/my-record/clinic'
      preLoaderRoute: typeof AuthenticatedMyRecordClinicRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/records': {
      id: '/_authenticated/my-record/records'
      path: '/records'
      fullPath: '/my-record/records'
      preLoaderRoute: typeof AuthenticatedMyRecordRecordsRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/resources': {
      id: '/_authenticated/my-record/resources'
      path: '/resources'
      fullPath: '/my-record/resources'
      preLoaderRoute: typeof AuthenticatedMyRecordResourcesRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/settings': {
      id: '/_authenticated/my-record/settings'
      path: '/settings'
      fullPath: '/my-record/settings'
      preLoaderRoute: typeof AuthenticatedMyRecordSettingsRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$id': {
      id: '/_authenticated/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof AuthenticatedPatientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/team/$id': {
      id: '/_authenticated/team/$id'
      path: '/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof AuthenticatedTeamIdRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/api/comms/drain': {
      id: '/api/comms/drain'
      path: '/api/comms/drain'
      fullPath: '/api/comms/drain'
      preLoaderRoute: typeof ApiCommsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights/events': {
      id: '/api/insights/events'
      path: '/api/insights/events'
      fullPath: '/api/insights/events'
      preLoaderRoute: typeof ApiInsightsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-record/plan/': {
      id: '/_authenticated/my-record/plan/'
      path: '/plan'
      fullPath: '/my-record/plan/'
      preLoaderRoute: typeof AuthenticatedMyRecordPlanIndexRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/plan/journal': {
      id: '/_authenticated/my-record/plan/journal'
      path: '/plan/journal'
      fullPath: '/my-record/plan/journal'
      preLoaderRoute: typeof AuthenticatedMyRecordPlanJournalRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/plan/routine': {
      id: '/_authenticated/my-record/plan/routine'
      path: '/plan/routine'
      fullPath: '/my-record/plan/routine'
      preLoaderRoute: typeof AuthenticatedMyRecordPlanRoutineRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/_authenticated/my-record/plan/timeline': {
      id: '/_authenticated/my-record/plan/timeline'
      path: '/plan/timeline'
      fullPath: '/my-record/plan/timeline'
      preLoaderRoute: typeof AuthenticatedMyRecordPlanTimelineRouteImport
      parentRoute: typeof AuthenticatedMyRecordRoute
    }
    '/api/comms/unsubscribe/$token': {
      id: '/api/comms/unsubscribe/$token'
      path: '/api/comms/unsubscribe/$token'
      fullPath: '/api/comms/unsubscribe/$token'
      preLoaderRoute: typeof ApiCommsUnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comms/webhooks/resend': {
      id: '/api/comms/webhooks/resend'
      path: '/api/comms/webhooks/resend'
      fullPath: '/api/comms/webhooks/resend'
      preLoaderRoute: typeof ApiCommsWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comms/webhooks/twilio': {
      id: '/api/comms/webhooks/twilio'
      path: '/api/comms/webhooks/twilio'
      fullPath: '/api/comms/webhooks/twilio'
      preLoaderRoute: typeof ApiCommsWebhooksTwilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/access/$token': {
      id: '/api/documents/access/$token'
      path: '/api/documents/access/$token'
      fullPath: '/api/documents/access/$token'
      preLoaderRoute: typeof ApiDocumentsAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMyRecordRouteChildren {
  AuthenticatedMyRecordAppointmentsRoute: typeof AuthenticatedMyRecordAppointmentsRoute
  AuthenticatedMyRecordBillingRoute: typeof AuthenticatedMyRecordBillingRoute
  AuthenticatedMyRecordClinicRoute: typeof AuthenticatedMyRecordClinicRoute
  AuthenticatedMyRecordRecordsRoute: typeof AuthenticatedMyRecordRecordsRoute
  AuthenticatedMyRecordResourcesRoute: typeof AuthenticatedMyRecordResourcesRoute
  AuthenticatedMyRecordSettingsRoute: typeof AuthenticatedMyRecordSettingsRoute
  AuthenticatedMyRecordIndexRoute: typeof AuthenticatedMyRecordIndexRoute
  AuthenticatedMyRecordPlanJournalRoute: typeof AuthenticatedMyRecordPlanJournalRoute
  AuthenticatedMyRecordPlanRoutineRoute: typeof AuthenticatedMyRecordPlanRoutineRoute
  AuthenticatedMyRecordPlanTimelineRoute: typeof AuthenticatedMyRecordPlanTimelineRoute
  AuthenticatedMyRecordPlanIndexRoute: typeof AuthenticatedMyRecordPlanIndexRoute
}

const AuthenticatedMyRecordRouteChildren: AuthenticatedMyRecordRouteChildren = {
  AuthenticatedMyRecordAppointmentsRoute:
    AuthenticatedMyRecordAppointmentsRoute,
  AuthenticatedMyRecordBillingRoute: AuthenticatedMyRecordBillingRoute,
  AuthenticatedMyRecordClinicRoute: AuthenticatedMyRecordClinicRoute,
  AuthenticatedMyRecordRecordsRoute: AuthenticatedMyRecordRecordsRoute,
  AuthenticatedMyRecordResourcesRoute: AuthenticatedMyRecordResourcesRoute,
  AuthenticatedMyRecordSettingsRoute: AuthenticatedMyRecordSettingsRoute,
  AuthenticatedMyRecordIndexRoute: AuthenticatedMyRecordIndexRoute,
  AuthenticatedMyRecordPlanJournalRoute: AuthenticatedMyRecordPlanJournalRoute,
  AuthenticatedMyRecordPlanRoutineRoute: AuthenticatedMyRecordPlanRoutineRoute,
  AuthenticatedMyRecordPlanTimelineRoute:
    AuthenticatedMyRecordPlanTimelineRoute,
  AuthenticatedMyRecordPlanIndexRoute: AuthenticatedMyRecordPlanIndexRoute,
}

const AuthenticatedMyRecordRouteWithChildren =
  AuthenticatedMyRecordRoute._addFileChildren(
    AuthenticatedMyRecordRouteChildren,
  )

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamIdRoute: typeof AuthenticatedTeamIdRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamIdRoute: AuthenticatedTeamIdRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMyRecordRoute: typeof AuthenticatedMyRecordRouteWithChildren
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRetentionRoute: typeof AuthenticatedRetentionRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedPatientsIdRoute: typeof AuthenticatedPatientsIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMyRecordRoute: AuthenticatedMyRecordRouteWithChildren,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRetentionRoute: AuthenticatedRetentionRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedPatientsIdRoute: AuthenticatedPatientsIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PortalRoute: PortalRoute,
  DTokenRoute: DTokenRoute,
  UTokenRoute: UTokenRoute,
  ApiCommsDrainRoute: ApiCommsDrainRoute,
  ApiInsightsEventsRoute: ApiInsightsEventsRoute,
  ApiCommsUnsubscribeTokenRoute: ApiCommsUnsubscribeTokenRoute,
  ApiCommsWebhooksResendRoute: ApiCommsWebhooksResendRoute,
  ApiCommsWebhooksTwilioRoute: ApiCommsWebhooksTwilioRoute,
  ApiDocumentsAccessTokenRoute: ApiDocumentsAccessTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
