import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import type {
  FullConfig,
  FullResult,
  Reporter,
  TestCase,
  TestResult,
} from "@playwright/test/reporter";

/**
 * Writes launch-plan/qc/REPORT.md: every check the specs recorded (via the
 * `qc` annotation in lib.ts), grouped by spec file, plus the known gaps that
 * are deliberately not fixed here.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(here, "../..");

type Row = {
  spec: string;
  project: string;
  test: string;
  check: string;
  result: string;
  note: string;
};

const KNOWN_GAPS = [
  "The app's mark and wordmark read SQINOS (profile redesign round 1); its route <title> strings and sign-in email copy still say Aetheria — a separate rename.",
  "`/about`, `/investors` and `/sitemap.xml` are listed in `gateway/routes.json` but have no page yet; they return the website 404 and nothing links to them.",
  "A path that is neither a website page nor an app route (a typo URL) is proxied to the app and shows the app's 404, whose Go home button lands on the website. The website's own 404 only appears under the website prefixes such as `/journal/…`.",
  "The brand link on token pages (`/d/<token>`, `/u/<token>`) goes to the app landing, which hands off to the website home; those pages need a signed token and are not exercised here.",
];

class QcReport implements Reporter {
  private rows: Row[] = [];
  private failures: string[] = [];
  private counts = { passed: 0, failed: 0, skipped: 0 };
  private baseURL = "";

  onBegin(config: FullConfig) {
    this.baseURL = String(config.projects[0]?.use.baseURL ?? "");
  }

  onTestEnd(test: TestCase, result: TestResult) {
    const spec = path.basename(test.location.file);
    const project = test.parent.project()?.name ?? "";
    if (result.status === "passed") this.counts.passed++;
    else if (result.status === "skipped") this.counts.skipped++;
    else {
      this.counts.failed++;
      this.failures.push(
        `${spec} › ${test.title} [${project}]: ${result.error?.message?.split("\n")[0] ?? result.status}`,
      );
    }
    // Runtime annotations live on the result (older Playwright mirrored them on
    // the test); read one source so every check is counted once.
    for (const a of result.annotations?.length ? result.annotations : test.annotations) {
      if (a.type !== "qc" || !a.description) continue;
      try {
        const e = JSON.parse(a.description) as { check: string; result: string; note?: string };
        this.rows.push({
          spec,
          project,
          test: test.title,
          check: e.check,
          result: e.result,
          note: e.note ?? "",
        });
      } catch {
        /* not ours */
      }
    }
  }

  onEnd(result: FullResult) {
    let sha = "";
    try {
      sha = execSync("git rev-parse --short HEAD", { cwd: ROOT, encoding: "utf8" }).trim();
    } catch {
      /* no git */
    }
    const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
    const mark = (r: string) =>
      ({ pass: "pass", fail: "**FAIL**", skip: "skipped", info: "info" })[r] ?? r;
    const bySpec = new Map<string, Row[]>();
    for (const r of this.rows) bySpec.set(r.spec, [...(bySpec.get(r.spec) ?? []), r]);
    const tally = (rows: Row[]) => {
      const c = { pass: 0, fail: 0, skip: 0, info: 0 } as Record<string, number>;
      for (const r of rows) c[r.result] = (c[r.result] ?? 0) + 1;
      return `${c.pass} pass · ${c.fail} fail · ${c.skip} skipped · ${c.info} info`;
    };
    const out: string[] = [
      "# Website ↔ demo app QC report",
      "",
      `Run ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC against \`${this.baseURL}\` at commit \`${sha}\`. Overall: **${result.status}**, ${this.counts.passed} tests passed, ${this.counts.failed} failed, ${this.counts.skipped} skipped.`,
      "",
      "Generated by `launch-plan/qc/run.sh` (Playwright: the demo app on 8094 behind the launch gateway on 8097, website from `launch-plan/website/dist`). Each table row is one check a spec recorded; a test can record many.",
      "",
    ];
    if (this.failures.length) {
      out.push("## Failures", "", ...this.failures.map((f) => `- ${esc(f)}`), "");
    }
    const order = [
      "routes.spec.ts",
      "links.spec.ts",
      "demo-entry.spec.ts",
      "return-paths.spec.ts",
      "gateway-health.spec.ts",
    ];
    for (const spec of [
      ...order.filter((s) => bySpec.has(s)),
      ...[...bySpec.keys()].filter((s) => !order.includes(s)),
    ]) {
      const rows = bySpec.get(spec)!;
      out.push(
        `## ${spec}`,
        "",
        `${tally(rows)}.`,
        "",
        "| Check | Device | Result | Note |",
        "| ----- | ------ | ------ | ---- |",
      );
      for (const r of rows)
        out.push(`| ${esc(r.check)} | ${r.project} | ${mark(r.result)} | ${esc(r.note)} |`);
      out.push("");
    }
    out.push("## Known gaps (not failures)", "", ...KNOWN_GAPS.map((g) => `- ${g}`), "");
    fs.writeFileSync(path.join(here, "REPORT.md"), out.join("\n"));
    console.log(
      `\nQC report: ${path.relative(ROOT, path.join(here, "REPORT.md"))} (${this.rows.length} checks)`,
    );
  }
}

export default QcReport;
