import { describe, expect, it } from "vitest";
import {
  buildInvoiceDocument,
  invoiceDate,
  invoiceDocumentHtml,
  invoiceMoney,
  invoicePeriodRange,
} from "@/lib/invoice-document";

const doc = buildInvoiceDocument({
  number: "INV-NR-2026-09",
  issuedOn: "2026-10-01",
  year: 2026,
  month: 9,
  from: {
    name: "Dr Nadia Rahman",
    line1: "Aesthetic Practitioner",
    line2: "nadia@aetheria.clinic",
  },
  billTo: { name: "Aetheria Medical", line1: "Payroll team", line2: "payroll@aetheria.clinic" },
  qty: 124,
  amount: 12773.25,
  note: 'Includes <the> "September" masterclass',
  status: "draft",
});

describe("buildInvoiceDocument", () => {
  it("fills the period label and the 14-day due date", () => {
    expect(doc.periodLabel).toBe("1–30 September 2026");
    expect(doc.dueOn).toBe("2026-10-15");
    expect(invoicePeriodRange(2026, 2)).toBe("1–28 February 2026");
    expect(invoiceDate("2026-10-01")).toBe("1 Oct 2026");
    expect(invoiceMoney(12773.25)).toBe("£12,773.25");
  });
  it("keeps an explicit due date", () => {
    expect(buildInvoiceDocument({ ...doc, year: 2026, month: 9, dueOn: "2026-10-31" }).dueOn).toBe(
      "2026-10-31",
    );
  });
});

describe("invoiceDocumentHtml", () => {
  const html = invoiceDocumentHtml(doc);
  it("carries every field of the mockup's layout", () => {
    for (const s of [
      "INVOICE",
      "INV-NR-2026-09",
      "Issued <strong",
      "1 Oct 2026",
      "15 Oct 2026",
      "From",
      "Bill to",
      "Dr Nadia Rahman",
      "Aetheria Medical",
      "Payroll team",
      "Treatments delivered, practitioner share",
      "1–30 September 2026",
      ">124<",
      "£12,773.25",
      "Adjustments",
      "£0.00",
      "Total due",
      "Generated by SQINOS from completed treatments in the diary.",
    ]) {
      expect(html).toContain(s);
    }
  });
  it("escapes the note and has no scripts or external assets", () => {
    expect(html).toContain("Includes &lt;the&gt; &quot;September&quot; masterclass");
    expect(html).not.toContain("<script");
    expect(html).not.toMatch(/src="http/);
  });
});
